
version: '3.8'
services:
  # app service for your backend
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: nest
      DATABASE_USER: ThienThanh
      DATABASE_PASS: 123@@
      DATABASE_URI: mongodb://192.168.1.62:27017
    ports:
      - '192.168.1.62:4000:4000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ThienThanh
      MONGO_INITDB_ROOT_PASSWORD: 123@@