
version: '3.8'
services:
  # app service for your backend
  app:
    container_name: backend
    image: backend-nest
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: nest
      DATABASE_USER: ThienThanh
      DATABASE_PASS: 123@@
      DATABASE_URI: mongodb://database:27017
    ports:
      - '4000:4000'
    networks:
      - mynetwork
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    networks:
      - mynetwork
    environment:
      MONGO_INITDB_ROOT_USERNAME: ThienThanh
      MONGO_INITDB_ROOT_PASSWORD: 123@@
networks:
  mynetwork:
    driver: bridge